url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
description: "Test text"


# Custom Settings

## Brand

contact_email: "info@polypheny.com"
support_email: "support@polypheny.com"

### Legal
copyright: "The Polypheny Project"

### Social Media
twitter_username: "polypheny"
youtube_channel: "polypheny"
linkedin_page: "polypheny"
github_repository: "https://github.com/polypheny/Polypheny-DB"





# Jekyll Collections
collections:
  about:
    output: true # Set to render files in _pages folder
    permalink: /:title/ # Set the format of the permalink by default 

sass:
    sass_dir: _sass


