url: "https://polypheny.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Polypheny Documenation" # the name of your site, e.g. ACME Corp.
short_title: "Documentation" # Will be capitilized
description:           >
  A self-adaptive Polystore that provides cost- and workload aware access to heterogeneous data.

# A shorter description for the sidebar.
tagline:               >
  The distributed and self-adaptive Polystore
# A list of keywords for your blog
keywords:              [polystore, distribution, databases, multi-stores, data, polydbms, nosql, sql]


homepage: "https://polypheny.com"

default_lang: en


# conifgs
include:
  - ".htaccess"

# Custom Settings

markdown: kramdown
highlighter: rouge
kramdown:
  parse_block_html: true
  syntax_highlighter: rouge

## Versioning
versions:
  stable: v0.8


## Brand

contact_email: "info@polypheny.com"
support_email: "support@polypheny.com"

### Legal
copyright: "Polypheny"

### Social Media
twitter_username: "polypheny"
youtube_channel: "UClwLro6vbAr0Ok0hjLvtovA"
linkedin_page: "polypheny"
github_repository: "polypheny/Polypheny-DB"


sass:
    sass_dir: _sass
