url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Polypheny Documenation" # the name of your site, e.g. ACME Corp.
short_title: "Documentation" # Will be capitilized
description:           >
  A self-adaptive Polystore that provides cost- and workload aware access to heterogeneous data.

# A shorter description for the sidebar.
tagline:               >
  The distributed and self-adaptive Polystore
# A list of keywords for your blog
keywords:              [polystore, distribution, databases, multi-stores, nosql, sql]


lang: en  
default_lang: en

# Custom Settings

## Versioning
versions:
  stable: v0.8


## Brand

contact_email: "info@polypheny.com"
support_email: "support@polypheny.com"

### Legal
copyright: "The Polypheny Project"

### Social Media
twitter_username: "polypheny"
youtube_channel: "UClwLro6vbAr0Ok0hjLvtovA"
linkedin_page: "polypheny"
github_repository: "polypheny/Polypheny-DB"





# Jekyll Collections
collections:
  about:
    output: true # Set to render files in _about folder
    permalink: /:title/ # Set the format of the permalink by default 

sass:
    sass_dir: _sass


